### PR TITLE
fix: remove url-loader && exclude output folder from svg loaders

### PR DESCRIPTION
**Pull request by andrewvasilchuk**

### CODE REVIEW

**Comment by andrewvasilchuk** [comment]
Relate [PR](https://github.com/nuxt-community/svg-sprite-module/pull/75).

**Comment by farnabaz** [comment]
Thanks

**Comment by andrewvasilchuk** [comment]
Can you please upload a new version on NPM?

**Comment by farnabaz** [comment]
Changes released on v0.3.0

**Comment by andrewvasilchuk** [comment]
@farnabaz , Thanks a lot!

**Pull request merged**
