### PR TITLE
fix(icons-page): prevent file not found error

### PR DESCRIPTION
**Pull request by haan123**
Fix nuxt-community#120

Check if nuxt-svg-sprite-icons-list.vue is existing then call extendRoutes else re-try

### CODE REVIEW

**Comment by haan123** [comment]
Hi @farnabaz 

Could you take a look on this?

**Comment by farnabaz** [comment]
Using set timeout is hacky and this may fail in large projects. I'm going to change this part a little.  
I appreciate if you confirm the fix after my changes

**Comment by haan123** [comment]
Yep, it is hakcy but Settimeout wil be called recursively ultil the file is created so i think it is safe in this way, but your fix is better, please merge it soon :D

**Comment by farnabaz** [comment]
Thank you

**Pull request merged**
